Task contact list (part_1)
MaxGmn/stud pull request #10
Opened 2019-05-10 13:48 UTC by MaxGmn

2019-05-13 08:00 UTC, vitaliiBoiarskyi commented on ContactList/ContactList/ViewControllerForUpdate.swift
> +class ViewControllerForUpdate: UIViewController {
updateViewController sounds better

2019-05-13 08:03 UTC, vitaliiBoiarskyi commented on ContactList/ContactList/ViewControllerForShow.swift
> +    var handler: ContactListHandler?
what it handles? contactListHnadler. Long names are OK.

2019-05-13 08:03 UTC, vitaliiBoiarskyi commented on ContactList/ContactList/ViewControllerForShow.swift
> +    @IBOutlet weak var firstName: UILabel!
I would add suffixes to control names. FirstNameLbl etc...

2019-05-13 08:05 UTC, vitaliiBoiarskyi commented on ContactList/ContactList/TableViewCell.swift
> +    @IBOutlet weak var cellName: UILabel!
Label prefix

2019-05-13 08:14 UTC, oleksii-lubianyi-epam requested changes

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +        self.image = image ?? UIImage(named: "emptyAvatar")!
You don't need to store empty avatar. Leave field as nil. Use default image for presentation purposes only

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +    func copy() -> Person{
You need to confirm NSCopying protocol instead

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +    static func == (lhs: Person, rhs: Person) -> Bool {
Is it working? As far as I know, method should be implemented out of class declaration

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +        controller.handler = self
`handler` mostly is being used with closures. `delegate` is mo suitable naming here

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +        if personsArray.isEmpty {
`numberOfSections(in tableView: UITableView) -> Int` is more suitable place to call this

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +        cell.cellImage.image = currentPerson.image
Add view model, instantiate it with necessary fields and call `cell.updateWith(viewModel)`

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForShow.swift
> +    var currentAttayIndex: Int!
You should not operate indexPath/index.
Add `contactId: String` into `Contact` and operate it.
Use `UUID().uuidString`

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForShow.swift
> +        let controller = self.storyboard!.instantiateViewController(withIdentifier: "ViewControllerForUpdate") as! ViewControllerForUpdate
How do you notify contactsList that contact updated/removed?

2019-05-13 08:14 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForUpdate.swift
> +    var currentPersonForEditing = Person()
What's the purpose of instantiating empty `Person` here?

2019-05-13 08:18 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForUpdate.swift
> +class ViewControllerForUpdate: UIViewController {
When keyboard is open, it's impossible to reach email field.
Return button doesn't work

2019-05-13 08:20 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForShow.swift
> +        self.present(navController, animated:true, completion: nil)
Edit should be pushed instead of presenting

2019-05-13 08:21 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/ViewControllerForUpdate.swift
> +        dismiss(animated: true, completion: nil)
You need to end editing before screen dismissal - keyboard remains on screen otherwise

2019-05-13 14:42 UTC, ghost approved these changes

2019-05-13 16:01 UTC, oleksii-lubianyi-epam requested changes

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +        return lhs.firstName == rhs.firstName && lhs.lastName == rhs.lastName && lhs.phoneNumber == rhs.phoneNumber && lhs.email == rhs.email && lhs.image == rhs.image
I am not sure you need to compare images here

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +func findItemIndex(by id: UUID, in array: [Person]) -> Int? {
I'd suggest to move this into controller

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +    private (set) var id: UUID
Let `id` be just `String`.
Use `UUID().uuidString`

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +        return 1
Return 0 for empty `personsArray`

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +    func updatePresonInformation(person: Person) {
Typo

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +    @IBOutlet weak var imageAreaTF: UIImageView!
`TF` says `textfield`, I think. Not applicable for UIImageView

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +            callback(currentPersonCopy)
`callback?(currentPersonCopy)` is ok

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +    var currentPersonForEditing: Person?
`var currentPersonForEditing: Person!`

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +        textField.resignFirstResponder()
It's enough top have either `textField.resignFirstResponder()`, or `view.endEditing(true)`

2019-05-13 16:01 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Validation.swift
> +func isValidEmail(email: String) -> Bool {
1. Global functions are evil. Wrap the into some class as static functions
2. Lot of copy-paste. Declare enumeration for validation cases, return regEx as calculated property.

2019-05-14 08:12 UTC, oleksii-lubianyi-epam requested changes

2019-05-14 08:12 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +    var imageState: ImageEditState!
`var imageState: ImageEditState = .noChanges`

2019-05-14 08:12 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +        firstNameTF.backgroundColor = firstNameValidationResult ? #colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0) : #colorLiteral(red: 0.8078431487, green: 0.02745098062, blue: 0.333333343
Replace hardcoded colors with struct and extension for `Bool` as discussed

2019-05-14 08:12 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Validation.swift
> +        return result && (kindOfField == .forTextField ? text.count <= 20 : true)
I'd recommend to move length limit into appropriate property of `enum ValidationFunctions`

2019-05-14 08:52 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewCell.swift
> +        cellImage.image = contact.image ?? Constants.emptyAvatar
Leave as it is for now.
In Iteration 2 please move this logics into view model to avoid any calculations in view/cell

2019-05-14 08:53 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +        for (key, value) in personsArray.enumerated() {
Please remove in Iteration 2

2019-05-14 09:02 UTC, oleksii-lubianyi-epam requested changes

2019-05-14 09:02 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/UpdateViewController.swift
> +    var currentPersonCopy = Person()
`var currentPersonCopy: Person!` as you're overwriting it on line 74

2019-05-14 09:02 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewCell.swift
> +        cellImage.image = contact.image ?? Constants.emptyAvatar
Please move this logics into view model to avoid any calculations in view/cell

2019-05-14 09:02 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/TableViewController.swift
> +    func findItemIndex(by id: String) -> Int? {
Remove method

2019-05-14 09:32 UTC, oleksii-lubianyi-epam requested changes

2019-05-14 09:32 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +class CellFieldsBuilder {
Bad naming. You don't build anything here, so why `Builder`?
```
struct PersonViewModel {
    let image: UIImage
    let lineFirst: String
    let lineSecond: String

    init(with contact: Contact) {
    ...
    }
}
```

2019-05-14 09:32 UTC, oleksii-lubianyi-epam commented on ContactList/ContactList/Model.swift
> +    static let emptyAvatar = UIImage(named: "emptyAvatar")
`UIImage(named: "emptyAvatar")!` to avoid unwrapping in project

2019-05-14 09:46 UTC, oleksii-lubianyi-epam approved these changes
Finally :)

2019-05-14 09:47 UTC, merged